version: '3'

services:
  prometheus-us-east-1:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-us-east-1.yml:/etc/prometheus/prometheus.yml
    environment:
      - AWS_ACCESS_KEY_ID=<AKIAZQLUA363YGZ6K3O6>
      - AWS_SECRET_ACCESS_KEY=<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>
      - AWS_REGION=af-south-1

  prometheus-us-west-1:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus-us-west-1.yml:/etc/prometheus/prometheus.yml
    environment:
      - AWS_ACCESS_KEY_ID=<AKIAZQLUA363YGZ6K3O6>
      - AWS_SECRET_ACCESS_KEY=<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>
      - AWS_REGION=eu-west-1

  prometheus-eu-west-3:
    image: prom/prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus/prometheus-eu-west-3.yml:/etc/prometheus/prometheus.yml
    environment:
      - AWS_ACCESS_KEY_ID=<AKIAZQLUA363YGZ6K3O6>
      - AWS_SECRET_ACCESS_KEY=<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>
      - AWS_REGION=eu-west-3

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
