version: '3'

services:
  prometheus-af-south-1:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-af-south-1.yml:/etc/prometheus/prometheus.yml
    

  prometheus-eu-west-1:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus/prometheus-eu-west-1.yml:/etc/prometheus/prometheus.yml

  prometheus-eu-west-3:
    image: prom/prometheus
    ports:
      - "9092:9090"
    volumes:
      - ./prometheus/prometheus-eu-west-3.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/my-site.conf:/etc/nginx/conf.d/my-site.conf

    


